### ISSUE TITLE
Изучить возможность реализации ios 14 app clips на RN

### ISSUE THREAD

**Issue by kasl** [pridemon/react-native-skeleton#11]
https://vc.ru/services/137617-mini-prilozheniya-app-clips-dlya-bystrogo-zapuska-servisov-kak-oni-rabotayut-chem-mogut-pomoch-biznesu-i-zachem-nuzhny-apple

https://developer.apple.com/app-clips/

Попробовать собрать вьюшку с любым контентом, из которой можно установить основную версию приложения.

**Comment by VEnom42** [comment]
Сделать аппклипс с помощью реакта можно, но всякие нативные фишки, типа показа оверлея с рекомендацией основного приложения придется реализовывать вручную в нейтиве (пока команда рн не добавит эти фичи).

Чтобы запилить аппклипс нужно в икскоде в нужном приложении создать новый таргет (`File -> New -> Target...`), там выбрать App Clip. 
<details>
  <summary>Скрин</summary>
  
![image](https://user-images.githubusercontent.com/30623613/94415150-69bb9780-01a7-11eb-97c4-f1008cfa47e5.png)
  
</details>

Обозвать его как-нибудь, поставить сториборд в интерфейсе, язык - обжектив-си. Можно было бы и свифт сразу, но не совсем ясно, как через свифт связаться с реактом. В примерах обжектив-си.
<details>
  <summary>Скрин настроек таргета</summary>
  
![image](https://user-images.githubusercontent.com/30623613/94417878-da17e800-01aa-11eb-8598-936c312a646d.png)

  
</details>

После создания у нас появится новая папка в проекте, с названием клипа. Первым делом идем, и добавляем поды в новый таргет. Открываем `Podfile`, добавляем туда строчку с новым таргетом.
```Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Babyname' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Google-Mobile-Ads-SDK'

  target 'BabynameTests' do
    inherit! :complete
    # Pods for testing
  end
  
  target 'BabynameClip' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

```

Далее идем в `Info.plist` клипса и устанавливаем там в `Bundle version string (short)` и `Bundle version` те же значения, что и в основном проекте. В случае бебинеймс, т.к. мы копируем все поды, а не только нужные для реакта пришлось еще добавить ключ адмоба (`GADApplicationIdentifier`). Далее копируем туда из основного проекта `App Transport Security Settings` целиком, нужно для загрузки `js`-бундла. Так же может потребоваться синхронизация `Required device capabilities` и `Supported interface orientations`. Ставим те же значения, что и в основном проекте.

После этого меняем легаси систему билдинга на актуальную (`File -> Workspace Settings -> Build System`), иначе, даже после удачной сборки аппклипс не запустится. Решаем проблемы, вызванные сменой билдера в основном приложении.

На этом этапе базовая подготовка завершена. Идем линкать реактовскую вьюху в нейтив. Открываем файл `ViewController.m`. Добавляем туда импорты:
```objective-c
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
```

Потом линкаем вьюху:
```objective-c
- (void)loadView {

  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.appclip" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"AppClip"
                                               initialProperties:nil
                                                   launchOptions:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  
  self.view = rootView;

}
```
<details>
  <summary>Полный код файла после изменений</summary>
  
```objective-c
#import "ViewController.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@interface ViewController ()

@end

@implementation ViewController

- (void)loadView {

  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.appclip" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"AppClip"
                                               initialProperties:nil
                                                   launchOptions:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  
  self.view = rootView;

}

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}


@end

```
  
</details>

Далее идем в `js`-код, и создаем там точку входа аппклипса `index.appclip.js`. Закидываем туда:
```js
import {AppRegistry, View, Text, Button} from 'react-native';
import React from 'react';

const AppClip = () => (
  <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
    <Text style={{fontSize: 22}}>React Native App Clip</Text>
    <Button title="Get Full App" color="#841584" />
  </View>
);

AppRegistry.registerComponent('AppClip', () => AppClip);

```

Теперь в икскоде выбираем таргет аппклипса (в моем случае `RNClip`)
<details>
  <summary>Скрин таргета</summary>
  
![image](https://user-images.githubusercontent.com/30623613/94421125-4e548a80-01af-11eb-8c8d-ad94b57fe602.png)

  
</details>

Проводим установку подов (`pod install`), запускаем билд клипса. Если все пройдет удачно, увидим в эмуляторе:
<details>
  <summary>Получившийся аппклипс</summary>
  
![image](https://user-images.githubusercontent.com/30623613/94421541-e6527400-01af-11eb-8022-8e1f593bed38.png)

</details>
Выглядит не очень эффектно, зато работает. Если же не работает, то вполне возможно нужно сделать новый свифт файл и указать в нем оба таргета (приложение и аппклипс), согласиться на бриджинг хедер.

<details>
  <summary>Создаем свифт файл</summary>
  
![image](https://user-images.githubusercontent.com/30623613/94421764-3af5ef00-01b0-11eb-9173-fb21b38818dd.png)

</details>

Далее идет настоящая магия: в аппклипсе есть нативный оверлей, который используют для [рекомендации](https://developer.apple.com/documentation/app_clips/recommending_an_app_clip_s_corresponding_app?language=objc) основного приложения из аппклипса. Самое забавное, что пример есть только на свифте. Поэтому необходимо решить несколько проблем: найти, как использовать свифтовый код в `objective-c`, и как запустить его из реакта. Первая проблема осложняется сложностью получения `UIWindowScene`, необходимой для запуска оверлея с рекомендацией. Как ее получить из ниоткуда в отдельном классе я не разобрался, каждый раз вместо сцены был `nil`. Консультировался с отделом айос разработки, там-таки подсказали, где где она хранится. 
Итого делаем свифт-файл в клипсе `Overlay.swift`.
```swift
import Foundation
import StoreKit
import UIKit

@objc class Overlay : NSObject {
  @objc func displayOverlay() {
    guard let windowScene = UIApplication.shared.windows.first(where: {$0.isKeyWindow})?.windowScene else { return }
    
    let config = SKOverlay.AppClipConfiguration(position: .bottom)
    let overlay = SKOverlay(configuration: config)
    
    overlay.present(in: windowScene)
  }
}
```
Для запуска метода `displayOverlay` в `objective-c` необходимо импортнуть файл `YourClipTargetName-Swift.h`
```objective-c
#import "RNClip-Swift.h"
```

<details>
  <summary>Тут есть небольшой подводный камень</summary>
  
Автогенерируемый для свифта `.h`-файл видоизменяет название метода с аргументом. Если бы, к примеру,  `displayOverlay` получал сцену извне:
```swift
import Foundation
import StoreKit
import UIKit

@objc class Overlay : NSObject {
  @objc func displayOverlay(windowScene: UIWindowScene) {
   
    let config = SKOverlay.AppClipConfiguration(position: .bottom)
    let overlay = SKOverlay(configuration: config)
    
    overlay.present(in: windowScene)
  }
}
```
То название метода в заголовочном файле выглядело бы так: `displayOverlayWithWindowSchene`. Поэтому лучше открывать этот файл и уточнять названия методов с аргументами :trollface: 
Чтобы он обновился, достаточно пересобрать аппклипс, даже если сборка сфейлится (просто тыкаем кнопку запуска).

</details>

После чего решаем вторую проблему - коннект с реактом. Создаем файлы `OverlayManager.h` и `OverlayManager.m`. В первом пишем:
```objective-c
#import <React/RCTBridgeModule.h>

@interface OverlayManager : NSObject <RCTBridgeModule>

@end

```
Во втором:
```objective-c
#import "OverlayManager.h"
#import <UIKit/UIKit.h>
#import "RNClip-Swift.h"

@implementation OverlayManager

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(displayOverlay)
{
  dispatch_sync(dispatch_get_main_queue(), ^{
    Overlay *overlay = [[Overlay alloc] init];
    [overlay displayOverlay];
  });
}


@end

```

Теперь можно апдейтнуть `js`-файл:
<details>
  <summary>Обновленный index.appclip.js</summary>
  
![image](https://user-images.githubusercontent.com/30623613/94421764-3af5ef00-01b0-11eb-9173-fb21b38818dd.png)
```js
import {AppRegistry, View, Text, Button, NativeModules} from 'react-native';
import React from 'react';

const {OverlayManager} = NativeModules;

const AppClip = () => (
  <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
    <Text style={{fontSize: 22}}>React Native App Clip</Text>
    <Button title="Get Full App" color="#841584" onPress={() => OverlayManager.displayOverlay()} />
  </View>
);

AppRegistry.registerComponent('AppClip', () => AppClip);

```
</details>

Теперь пересобираем, и по тычку кнопки у нас появляется оверлей. Часть с вызовом оверлея свободно можно вынести в отдельный репозиторий и ставить в каждом приложении отдельно, как RN-модуль.

Полезный видос про аппклипсы - https://developer.apple.com/videos/play/wwdc2020/10146/

Продолжение следует. Следующая часть будет про шаринг избранного из `Babynames-ru` с помощью аппклипса.

**Comment by VEnom42** [comment]
> После этого меняем легаси систему билдинга на актуальную (File -> Workspace Settings -> Build System), иначе, даже после удачной сборки аппклипс не запустится. Решаем проблемы, вызванные сменой билдера в основном приложении.

Вот тут, на всякий случай остановлюсь подробнее. В бебинеймс была проблема с дублированием шрифтов из `react-native-vector-icons`. Они копировались в двух фазах билда: `Copy Bundle Resources` и `[CP] Copy Pods Resources`. В старых версиях мы руками добавляли эти шрифты в первый пункт, а потом библиотека начала делать это автоматом во второй пункт. После удаления добавленных вручную шрифтов все собирается с новой системой билдинга.

> Следующая часть будет про шаринг избранного из Babynames-ru с помощью аппклипса.

Шаринг реализуется с помощью передачи параметров через ссылку. В основном приложении делаем эту ссылку, действует она практически как [universal link](https://developer.apple.com/ios/universal-links/), с той разницей, что при клике на нее открывает карту аппклипса (а вернее, при клике на нее переходим на веб-страницу с каким-то контентом, и баннером, при клике на который появится карта аппклипса). Есть три варианта результатов, которые можно получить при тычке на эту ссылку: при версии `ios` < 14 - открывается приложение, если установлено, иначе открывается страница в сторе, версия `ios` = 14 - открывается карта аппклипса, либо само приложение, если оно установлено.

Чтобы ссылка работала именно таким образом, нужно настроить [associated domains](https://developer.apple.com/documentation/safariservices/supporting_associated_domains?language=objc). Для этого необходимо связать приложение и аппклипс с каким-либо доменом. В аппклипсе в настройках таргета в `Signing & Capabilities` добавляем `associated domains`, туда пишем `appclips:wachanga.com/babynames`. На самом wachanga.com/babynames кладем файлик `wachanga.com/babynames/.well-known/apple-app-site-association` с содержанием:
```json
{  
  "appclips": {
    "apps": ["H8WR727FR8.com.wachanga.babyname.share-clip"]
  }
}
```
Где `H8WR727FR8` - айдишник команды, а `com.wachanga.babyname.share-clip` - `bundle id` аппклипса. Так же на самой страничке `wachanga.com/babynames` необходимо указать метатег с данными приложения и аппклипса, по которым будет автоматом генерироваться баннер -` <meta name=“apple-itunes-app” content=“app-id=1371573370, app-clip-bundle-id=com.wachanga.babyname.share-clip”>`. 

Чтобы потестить аппклипс в тестфлайте, необходимо ~~пройти 7 кругов ада~~ произвести необходимые апдейты того, что было сделано в [первом посте](https://github.com/pridemon/react-native-skeleton/issues/11#issuecomment-699996869), настроить в коннекте [App Clip Invocation](https://help.apple.com/app-store-connect/#/devbc57e2ec6). С этого момента аппклипс должен открываться при тычке на баннер (так же аппклипс можно открыть из тестфлайта, там будет пункт "блиц приложение". Чтобы открывалась карта аппклипса нужно провести еще [ряд настроек](https://medium.com/@emcro/setting-up-and-testing-app-clips-in-ios-14-3d5ac193d1bc), на этот раз уже на устройстве. При релизе приложения с аппклипсом карта настраивается в коннекте.

Проблемы, возникшие с теми настройками, что были в первом посте:

Приложение собиралось, отправлялось, но заворачивалось с ошибкой про несоответствие версий основного приложения.и аппклипса. Тут просто добавили в сборку тот же апдейт версии аппклипсу, что и у основного приложения.

Приложение собиралось, отправлялось, принималось коннектом, но заворачивалось на стадии обработки загруженного билда. Симптомы: приложение отправлось, в коннекте не появилось, или появилось на некоторое время (в приложении, со статусом "обрабатывается"), и пропало. И кому-то, не ясно кому (или всем, кроме обладателей роли разработчика) приходит письмо на почту, с описанием ошибки (может попасть в спам).
<details>
  <summary>Письмо</summary>

```
Dear Developer,
We identified one or more issues with a recent delivery for your app, “Имена для ребенка русские” 3.3.3 (3.3.3.688). Please correct the following issues, then upload again.
ITMS-90713: Missing Info.plist value - A value for the Info.plist key ‘CFBundleIconName’ is missing in the bundle ‘com.wachanga.babyname.share-clip’. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7.
Best regards,
The App Store Team
```

</details>
Эта ошибка исправилась путем копирования иконки основного приложения в таргет аппклипса, и добавлением соответствующего пункта в `info.plist`. Забавно то, что в основном приложении есть пункт в настройках, а в аппклипсе нет, и я не нашел, как его добавить.
<details>
  <summary>Настройки</summary>
  
 ![image](https://user-images.githubusercontent.com/30623613/96409863-2e454380-1210-11eb-806d-09b84e937bf7.png)
  
</details>

Следующая ошибка пришла так же на почту, проблема была в превышении ограничения в 10 мб. Причем аппклипс в запакованном виде, в котором он загружается пользователю, не превышал 4.5 мб, а вот разархивированная `universal ipa`, единственная, превысившая ограничение, весила 10.2 мб. После анализа внутренностей, стало ясно, что можно уменьшить вес до нужного, удалив те самые шрифты их вектор иконок, там их было примерно на 1 мб. Но это несколько костыльно, основная проблема - лишние поды. После редактирования подфайла (таргет аппклипса был вынесен отдельно, и там прописаны скрипты, которые устанавливают необходимые для реакта поды и флиппер.
<details>
  <summary>Подфайл после апдейта</summary>
  
 ```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Babyname' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Google-Mobile-Ads-SDK'

  target 'BabynameTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNClip' do
  use_react_native!
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
end

```
  
</details> 

Теперь приложение стало весить 2.8 мб в разархивированном состоянии. Лишние поды весили очень много.

Дальше билд загрузился, апрувнулся, но аппклипс крашился при запуске. После сравнения содержимое архива основного приложения и аппклипса, обнаружилось отсутствие `js`-бундла в последнем. Оказалось, необходимо добавить фазу билда `Bundle React Native code and images`. Но в стандартном варианте это раздуло аппклипс до 40+ мб. `js` собрался по точке входа основного приложения, с соответствующими подключениями крупных `json`-ок. После анализа внутренностей скрипта, оказалось, что он принимает индексный файл аргументом. После добавления нужного аргумента, аппклипс увеличился до 3.5 мб в разархивированном состоянии, и обзавелся своим собственным `js`-бундлом.
<details>
  <summary>Скрин фазы билда с аргументом</summary>
  
 ![image](https://user-images.githubusercontent.com/30623613/96411909-70bc4f80-1213-11eb-9533-27d33dd969f5.png)
  
</details>

С этого момента аппклипс прекратил крашится при запуске.

Теперь можно поговорить о получении ссылки. В `SceneDelegate` есть два метода, из которых можно до нее добраться - `continueUserActivity` и `willConnectToSession`. Первый получает [NSUserActivity](https://developer.apple.com/documentation/foundation/nsuseractivity?language=objc) в качестве аргумента, в этом объекте есть свойство `webpageURL`. Во втором методе до ссылки можно добраться через [UISceneConnectionOptions](https://developer.apple.com/documentation/uikit/uisceneconnectionoptions?language=objc), в котором есть [userActivities](https://developer.apple.com/documentation/uikit/uisceneconnectionoptions/3238074-useractivities?language=objc). Сперва получение ссылки было только в первом методе, и иногда при загрузке этот метод не вызывадся, и код получения ссылки не испольнялся. После добавления того же кода во второй метод, случаев отсутствия ссылки больше не было. В [коде](https://github.com/AppsFlyerSDK/appsflyer-apple-app-clips-sample-app/blob/master/Fruit%20AppClip/SceneDelegate.swift) демо приложения с аппклипсом так же получают ссылку в обоих методах.

Были некоторые проблемы с отправкой этой ссылки в `js` - пришлось заглянуть в бридж, и откопать метод, который бы возвращал что-то в `js`, без колбэков и ивентов. Такой нашелся - `RCT_EXPORT_SYNCHRONOUS_TYPED_METHOD`.

Еще были проблемы с ошибками `js`, при возникновении которых летел нативный краш, и чтобы продолжить работу, необходимо было перезапустить аппклипс в икскоде. Первая попытка исправить ситуацию - сделать такой же коннект в `AppDelegate`, как в [демо приложении](https://github.com/facebook/react-native/blob/v0.63.3/template/ios/HelloWorld/AppDelegate.m) реакта. Ничего не вышло, вместо реактовской вьюхи был белый экран, и в то же время консольлоги из `js`-а отображались. Ошибки не крашили нейтив, но все тот же белый экран. Следующим вариантом было законнектить так же через `ViewController`, как и раньше, но с передачей бриджу `AppDelegate`-а, вместо прямой ссылки на `js`. В этом варианте было видно реактовскую вьюху, нейтив не крашился `js`- ыми ошибками. Но вместо красивого, красного логбокса с описанием ошибки - белый экран. Но описание ошибки падает в консоль с дев сервером, поэтому данный вариант гораздо удобнее, чем нативный краш.
<details>
  <summary>ViewController.m</summary>
  
 ```objective-c
#import "ViewController.h"
#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTBridge.h>

@interface ViewController ()

@end

@implementation ViewController

- (void)loadView {
  
  AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:appDelegate launchOptions:appDelegate.launchOptions];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"AppClip"
                                            initialProperties:nil];
  
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  
  self.view = rootView;
  [appDelegate.window makeKeyAndVisible];

}

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}


@end
```
  
</details>
<details>
  <summary>AppDelegate.h</summary>
  
  ```objective-c
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>

@property (nonatomic, strong) UIWindow *window;
@property (nonatomic, strong) NSDictionary *launchOptions;

@end

  ```
  
</details>
<details>
  <summary>AppDelegate.m</summary>
  
Тут нужно обязательно определить метод `sourceURLForBridge` с указанием положения `js` -а.

  ```objective-c
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  self.launchOptions = launchOptions;
  
  return YES;
}

#pragma mark - UISceneSession lifecycle


- (UISceneConfiguration *)application:(UIApplication *)application configurationForConnectingSceneSession:(UISceneSession *)connectingSceneSession options:(UISceneConnectionOptions *)options {
    // Called when a new scene session is being created.
    // Use this method to select a configuration to create the new scene with.
    return [[UISceneConfiguration alloc] initWithName:@"Default Configuration" sessionRole:connectingSceneSession.role];
}


- (void)application:(UIApplication *)application didDiscardSceneSessions:(NSSet<UISceneSession *> *)sceneSessions {
    // Called when the user discards a scene session.
    // If any sessions were discarded while the application was not running, this will be called shortly after application:didFinishLaunchingWithOptions.
    // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.appclip" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end


  ```
  
</details>

**Comment by kasl** [comment]
@VEnom42 прикрепи сюда код/ветку плиз

**Comment by VEnom42** [comment]
https://github.com/pridemon/babynames-reactnative/tree/app_clips_test
